[package]
name = "rknn-rs"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "rknn rust binding"
repository = "https://github.com/darkautism/rknn-rs"

[dependencies]
bytemuck = "1.23.1"

[build-dependencies]
bindgen = "0.72.0"




